[window]
fullscreen = true

[demo]
mode = "random"
effect_duration = 60
transition = "shuffle"

[audio]
reactivity = 2.25
latency = "high"
try_alsa_loopback = false

[ansi]
ansi_dir_auto = "assets/ansi/acid"
ansi_own_dir = "assets/ansi"
ansi_acid_dir = "assets/ansi/acid"

[playlist]
start_effect = "Audio Spectrum"

[logging]
level = "INFO"

[recording]
auto_record = true
directory = "recordings"
capture_audio = true

[overlays]
flash_messages = false
