"""Guards for the free-threaded (cp314t) wheel build recipe.

``tools/packaging/build_ft_wheels.sh`` builds moderngl, glcontext and
python-rtmidi as cp314t manylinux wheels (none exist upstream).  The recipe
pins source versions *and* sdist hashes, so the one thing that can rot
silently is the pin drifting from what ``requirements.txt`` ships on the
GIL builds -- the free-threaded wheels would then be a different version
from the one the app was tested against.  These tests keep that honest and
check the scripts at least parse.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / 'tools' / 'packaging' / 'build_ft_wheels.sh'
SMOKE = ROOT / 'tools' / 'packaging' / 'ft_wheels_smoke.py'
PIN = re.compile(r'^PIN_(?P<name>[a-z_]+)="(?P<ver>[0-9][0-9.]*) (?P<sha>[0-9a-f]{64})"$', re.M)


def _pins() -> dict[str, tuple[str, str]]:
    return {m['name']: (m['ver'], m['sha']) for m in PIN.finditer(BUILD.read_text())}


def test_recipe_pins_all_three_packages_with_hashes() -> None:
    assert set(_pins()) == {'moderngl', 'glcontext', 'python_rtmidi'}


@pytest.mark.parametrize('name, req', [('moderngl', 'moderngl'),
                                       ('python_rtmidi', 'python-rtmidi')])
def test_pins_match_requirements_txt(name: str, req: str) -> None:
    wanted = re.search(rf'^{re.escape(req)}==([0-9.]+)', (ROOT / 'requirements.txt').read_text(), re.M)
    assert wanted is not None, f'{req} is no longer pinned in requirements.txt'
    assert _pins()[name][0] == wanted.group(1), (
        f'{req}: requirements.txt says {wanted.group(1)} but the cp314t recipe builds {_pins()[name][0]}')


@pytest.mark.skipif(shutil.which('bash') is None, reason='no bash')
def test_build_script_parses() -> None:
    subprocess.run(['bash', '-n', str(BUILD)], check=True)


def test_smoke_script_compiles() -> None:
    compile(SMOKE.read_text(), str(SMOKE), 'exec')


def test_cython_pin_understands_free_threading() -> None:
    """python-rtmidi's sdist carries C++ generated by Cython 3.0.5, which
    predates free-threading support; the recipe regenerates it, so the Cython
    it names must be at least 3.1."""
    m = re.search(r'^CYTHON_VERSION="(\d+)\.(\d+)\.\d+"$', BUILD.read_text(), re.M)
    assert m is not None
    assert (int(m[1]), int(m[2])) >= (3, 1)
    assert 'rm -f "$tree/src/_rtmidi.cpp"' in BUILD.read_text()
