"""Guards for the free-threaded (cp314t) wheel build recipe.

``tools/packaging/build_ft_wheels.sh`` builds moderngl, glcontext and
python-rtmidi as cp314t manylinux wheels (none exist upstream).  The recipe
pins source versions *and* sdist hashes, so the one thing that can rot
silently is the pin drifting from what ``requirements.txt`` ships on the
GIL builds -- the free-threaded wheels would then be a different version
from the one the app was tested against.  These tests keep that honest and
check the scripts at least parse.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / 'tools' / 'packaging' / 'build_ft_wheels.sh'
SMOKE = ROOT / 'tools' / 'packaging' / 'ft_wheels_smoke.py'
PIN = re.compile(r'^PIN_(?P<name>[a-z_]+)="(?P<ver>[0-9][0-9.]*) (?P<sha>[0-9a-f]{64})"$', re.M)


def _pins() -> dict[str, tuple[str, str]]:
    return {m['name']: (m['ver'], m['sha']) for m in PIN.finditer(BUILD.read_text())}


def test_recipe_pins_all_three_packages_with_hashes() -> None:
    assert set(_pins()) == {'moderngl', 'glcontext', 'python_rtmidi'}


@pytest.mark.parametrize('name, req', [('moderngl', 'moderngl'),
                                       ('python_rtmidi', 'python-rtmidi')])
def test_pins_match_requirements_txt(name: str, req: str) -> None:
    wanted = re.search(rf'^{re.escape(req)}==([0-9.]+)', (ROOT / 'requirements.txt').read_text(), re.M)
    assert wanted is not None, f'{req} is no longer pinned in requirements.txt'
    assert _pins()[name][0] == wanted.group(1), (
        f'{req}: requirements.txt says {wanted.group(1)} but the cp314t recipe builds {_pins()[name][0]}')


@pytest.mark.skipif(shutil.which('bash') is None, reason='no bash')
def test_build_script_parses() -> None:
    subprocess.run(['bash', '-n', str(BUILD)], check=True)


def test_smoke_script_compiles() -> None:
    compile(SMOKE.read_text(), str(SMOKE), 'exec')


def test_cython_pin_understands_free_threading() -> None:
    """python-rtmidi's sdist carries C++ generated by Cython 3.0.5, which
    predates free-threading support; the recipe regenerates it, so the Cython
    it names must be at least 3.1."""
    m = re.search(r'^CYTHON_VERSION="(\d+)\.(\d+)\.\d+"$', BUILD.read_text(), re.M)
    assert m is not None
    assert (int(m[1]), int(m[2])) >= (3, 1)
    assert 'rm -f "$tree/src/_rtmidi.cpp"' in BUILD.read_text()


OPENCV_BUILD = ROOT / 'tools' / 'packaging' / 'build_ft_opencv_wheel.sh'
OPENCV_SMOKE = ROOT / 'tools' / 'packaging' / 'ft_opencv_smoke.py'
OPENCV_CONTAINERFILE = ROOT / 'tools' / 'packaging' / 'ft-opencv' / 'Containerfile'


def test_opencv_recipe_builds_the_pinned_version() -> None:
    """PyPI has no sdist for the pinned opencv-python-headless, so the recipe
    builds the matching git tag; its version must not drift from the pin."""
    wanted = re.search(r'^opencv-python-headless==([0-9.]+)', (ROOT / 'requirements.txt').read_text(), re.M)
    assert wanted is not None
    recipe = re.search(r'^OPENCV_PYTHON_VERSION="([0-9.]+)"$', OPENCV_BUILD.read_text(), re.M)
    assert recipe is not None and recipe[1] == wanted[1]
    assert re.search(r'^OPENCV_PYTHON_COMMIT="[0-9a-f]{40}"$', OPENCV_BUILD.read_text(), re.M)
    assert re.search(r'^OPENCV_COMMIT="[0-9a-f]{40}"$', OPENCV_BUILD.read_text(), re.M)


def test_opencv_recipe_drops_the_limited_api_flag() -> None:
    """The stable ABI cannot exist on a free-threaded build."""
    assert "PYTHON3_LIMITED_API=ON" in OPENCV_BUILD.read_text()  # the sed that removes it
    assert "sed -i '/\"-DPYTHON3_LIMITED_API=ON\",/d' setup.py" in OPENCV_BUILD.read_text()


def test_opencv_ffmpeg_stays_lgpl() -> None:
    """The wheel is redistributed: FFmpeg must stay plain LGPL."""
    text = OPENCV_CONTAINERFILE.read_text()
    configure = text[text.index('./configure --prefix=/ffmpeg_build \\\n        --extra-cflags'):]
    for flag in ('--enable-gpl', '--enable-nonfree', '--enable-version3', '--enable-libx264',
                 '--enable-libx265', '--enable-openssl', '--enable-libfdk'):
        assert flag not in configure, f'{flag} would make the bundled FFmpeg non-LGPL'
    assert re.search(r'^ARG FFMPEG_SHA256=[0-9a-f]{64}$', text, re.M)
    assert re.search(r'^ARG VPX_COMMIT=[0-9a-f]{40}$', text, re.M)


@pytest.mark.skipif(shutil.which('bash') is None, reason='no bash')
def test_opencv_script_parses() -> None:
    subprocess.run(['bash', '-n', str(OPENCV_BUILD)], check=True)
    compile(OPENCV_SMOKE.read_text(), str(OPENCV_SMOKE), 'exec')


SPHN_BUILD = ROOT / 'tools' / 'packaging' / 'build_ft_sphn_wheel.sh'
SPHN_CONTAINERFILE = ROOT / 'tools' / 'packaging' / 'ft-sphn' / 'Containerfile'


def test_sphn_recipe_pins_source_and_toolchain() -> None:
    text = SPHN_BUILD.read_text()
    assert re.search(r'^SPHN_VERSION="[0-9.]+"$', text, re.M)
    assert re.search(r'^SPHN_SDIST_SHA256="[0-9a-f]{64}"$', text, re.M)
    container = SPHN_CONTAINERFILE.read_text()
    assert re.search(r'^ARG RUST_VERSION=[0-9.]+$', container, re.M)
    assert re.search(r'^ARG RUSTUP_INIT_SHA256=[0-9a-f]{64}$', container, re.M)
    assert re.search(r'^ARG MATURIN_VERSION=1\.[0-9.]+$', container, re.M)   # sphn needs maturin <2
    assert '--locked' in text            # the Rust dependency set is the sdist's Cargo.lock


@pytest.mark.skipif(shutil.which('bash') is None, reason='no bash')
def test_sphn_script_parses() -> None:
    subprocess.run(['bash', '-n', str(SPHN_BUILD)], check=True)
    compile((ROOT / 'tools' / 'packaging' / 'ft_sphn_smoke.py').read_text(), 'ft_sphn_smoke.py', 'exec')


def test_opencv_smoke_clips_written_without_ffmpeg_have_content_in_every_frame(tmp_path) -> None:
    """Windows CI runners have no system ffmpeg, so the smoke test writes its own clips
    with cv2.  The first version made frame 0 all black, and the check that rejects a
    blank first frame failed a good wheel (an hour of CI to find out)."""
    cv2 = pytest.importorskip('cv2')
    import importlib.util
    import sys as _sys
    spec = importlib.util.spec_from_file_location('ft_opencv_smoke_t', OPENCV_SMOKE)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    _sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    clips = mod._make_clips_with_cv2(cv2, tmp_path)
    assert clips, 'cv2 could not write any clip'
    for path in clips.values():
        cap = cv2.VideoCapture(str(path))
        ok, first = cap.read()
        cap.release()
        assert ok and float(first.std()) >= 5, f'{path.name}: first frame is blank'
