"""Fit a lightweight ridge-regression weight set from a local corpus.

The live app does not depend on this script. It is an offline training tool for
turning a labeled corpus into portable model weights and normalization stats.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from training_lib import (
    DEFAULT_FEATURE_COLUMNS,
    as_jsonable,
    fit_ridge_weights,
    load_jsonl_rows,
    utc_now_iso,
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'corpus',
        type=Path,
        help='Path to the JSONL corpus generated by build_corpus.py.',
    )
    parser.add_argument(
        '--target-column',
        default='target_score',
        help='Numeric label column to fit against.',
    )
    parser.add_argument(
        '--feature-column',
        action='append',
        dest='feature_columns',
        help='Feature column to include in the regression; repeat to override the default set.',
    )
    parser.add_argument(
        '--ridge',
        type=float,
        default=1.0,
        help='Ridge penalty applied during the fit.',
    )
    parser.add_argument(
        '--out',
        type=Path,
        default=Path('assets/training/models/latest-weights.json'),
        help='Output JSON file for the fitted weight set.',
    )
    return parser.parse_args()


def main() -> int:
    """Entry point for the offline weight-fitting CLI."""

    args = _parse_args()
    rows = load_jsonl_rows(args.corpus)
    feature_columns = args.feature_columns or DEFAULT_FEATURE_COLUMNS
    fit = fit_ridge_weights(rows, args.target_column, feature_columns, args.ridge)
    payload = {
        'generated_at': utc_now_iso(),
        'corpus_path': str(args.corpus),
        'target_column': args.target_column,
        'feature_columns': fit.feature_columns,
        'feature_means': fit.feature_means,
        'feature_stds': fit.feature_stds,
        'weights': fit.weights,
        'bias': fit.bias,
        'metrics': fit.metrics,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(as_jsonable(payload), indent=2, sort_keys=True) + '\n', encoding='utf-8')
    print(json.dumps(as_jsonable(payload), sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())