#!/usr/bin/env python3
"""Generate procedural USD simulation scenes for the sims-01 drop-in.

Every file produced by this script is noted as
"Procedurally generated by GitHub Copilot" in its USDA doc string.

Run from the repo root:
    .venv/bin/python3 tools/gen_sim_scenes.py
"""
from __future__ import annotations

import math
import random
import pathlib

import numpy as np

SCENES = pathlib.Path("drop-ins/sims-01/scenes")
SCENES.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# USDA serialisation helpers
# ---------------------------------------------------------------------------

def _fpts(pts: np.ndarray | list) -> str:
    """Format an (N,3) array as a USDA point3f[] literal."""
    if not isinstance(pts, list):
        pts = pts.tolist()
    return "[" + ", ".join(f"({p[0]:.5f}, {p[1]:.5f}, {p[2]:.5f})" for p in pts) + "]"


def _ffl(vals: np.ndarray | list) -> str:
    """Format a 1-D array as a USDA float[] literal."""
    if not isinstance(vals, list):
        vals = vals.tolist()
    return "[" + ", ".join(f"{v:.5f}" for v in vals) + "]"


def _fint(vals: np.ndarray | list) -> str:
    """Format a 1-D array as a USDA int[] literal."""
    if not isinstance(vals, list):
        vals = vals.tolist()
    return "[" + ", ".join(str(int(v)) for v in vals) + "]"


def _ts(frames: dict[int, np.ndarray]) -> str:
    """Render a dict {timecode: (N,3) array} as a USDA timeSamples block."""
    lines = ["{\n"]
    for tc in sorted(frames):
        lines.append(f"            {tc}: {_fpts(frames[tc])},\n")
    lines.append("        }")
    return "".join(lines)


def _header(doc: str, start: int = 1, end: int = 1, fps: int = 24) -> str:
    tc = ""
    if end > start:
        tc = (
            f"    startTimeCode = {start}\n"
            f"    endTimeCode   = {end}\n"
            f"    timeCodesPerSecond = {fps}\n"
        )
    return (
        f"#usda 1.0\n(\n    doc = \"{doc}\"\n    upAxis = \"Y\"\n"
        f"    metersPerUnit = 0.01\n{tc})\n\n"
    )


def _write(name: str, content: str) -> None:
    p = SCENES / name
    p.write_text(content)
    kb = len(content) // 1024
    print(f"  {name:<42s}  {kb:>5d} KB")


# ---------------------------------------------------------------------------
# 1 – GALAXY SPIRAL  (static Points — 6 000 pts)
# ---------------------------------------------------------------------------

def gen_galaxy_spiral() -> None:
    """3-armed logarithmic spiral galaxy — static particle cloud."""
    rng = np.random.default_rng(42)
    n_arm, n_core = 2000, 600
    parts = []
    for arm in range(3):
        base = arm * 2 * math.pi / 3
        t = rng.uniform(0.05, 1.0, n_arm) ** 0.6 * 5.0
        theta = base + t * 1.6 + rng.normal(0, 0.18, n_arm)
        x = t * np.cos(theta) + rng.normal(0, 0.12, n_arm)
        z = t * np.sin(theta) + rng.normal(0, 0.12, n_arm)
        y = rng.normal(0, 0.06 * (1 - t / 5.5), n_arm)
        parts.append(np.column_stack([x, y, z]))
    r = rng.standard_exponential(n_core) * 0.4
    a = rng.uniform(0, 2 * math.pi, n_core)
    parts.append(np.column_stack([r * np.cos(a), rng.normal(0, 0.08, n_core), r * np.sin(a)]))
    pts = np.vstack(parts).astype(np.float32)
    widths = [0.04] * len(pts)
    body = _header("Procedurally generated by GitHub Copilot — 3-armed spiral galaxy (static)")
    body += (
        "def Points \"Galaxy\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("galaxy_spiral.usda", body)


# ---------------------------------------------------------------------------
# 2 – DNA DOUBLE HELIX  (static Points — ~1 500 pts)
# ---------------------------------------------------------------------------

def gen_dna_double_helix() -> None:
    """DNA double-helix with backbone and base-pair rungs — static."""
    rng = np.random.default_rng(7)
    n_turns, pts_per_turn = 8, 24
    n = n_turns * pts_per_turn
    t = np.linspace(0, n_turns * 2 * math.pi, n)
    r = 0.9
    # Two backbones
    x1 = r * np.cos(t);      x2 = r * np.cos(t + math.pi)
    z1 = r * np.sin(t);      z2 = r * np.sin(t + math.pi)
    y  = np.linspace(-n_turns, n_turns, n)
    b1 = np.column_stack([x1, y, z1])
    b2 = np.column_stack([x2, y, z2])
    # Base-pair rungs (every 3rd step)
    rung_pts = []
    for i in range(0, n, 3):
        steps = 8
        lam = np.linspace(0, 1, steps)
        for l in lam:
            rung_pts.append(b1[i] * (1 - l) + b2[i] * l)
    rung_pts = np.array(rung_pts, dtype=np.float32)
    # Small sugar/phosphate blobs on the backbones
    noise = rng.normal(0, 0.04, (n, 3)).astype(np.float32)
    pts = np.vstack([b1 + noise, b2 + noise, rung_pts]).astype(np.float32)
    widths = ([0.10] * len(b1) + [0.10] * len(b2) + [0.06] * len(rung_pts))
    body = _header("Procedurally generated by GitHub Copilot — DNA double helix (static)")
    body += (
        "def Points \"DNAHelix\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("dna_double_helix.usda", body)


# ---------------------------------------------------------------------------
# 3 – FCC CRYSTAL LATTICE  (static Points — ~2 000 pts)
# ---------------------------------------------------------------------------

def gen_crystal_fcc() -> None:
    """Face-centred cubic crystal — two species, static."""
    pts_a, pts_b = [], []
    extent = 4
    # FCC basis: corner + face-centre offsets
    basis = [
        (0, 0, 0), (0.5, 0.5, 0), (0.5, 0, 0.5), (0, 0.5, 0.5),
    ]
    for ix in range(-extent, extent + 1):
        for iy in range(-extent, extent + 1):
            for iz in range(-extent, extent + 1):
                for bx, by, bz in basis:
                    px = (ix + bx) * 0.5
                    py = (iy + by) * 0.5
                    pz = (iz + bz) * 0.5
                    if (ix + iy + iz) % 2 == 0:
                        pts_a.append((px, py, pz))
                    else:
                        pts_b.append((px, py, pz))
    # Trim to sphere
    r_max = 2.2
    pts_a = [(x, y, z) for x, y, z in pts_a if x*x + y*y + z*z < r_max**2]
    pts_b = [(x, y, z) for x, y, z in pts_b if x*x + y*y + z*z < r_max**2]
    pts = np.array(pts_a + pts_b, dtype=np.float32)
    widths = [0.14] * len(pts_a) + [0.09] * len(pts_b)
    body = _header("Procedurally generated by GitHub Copilot — FCC crystal lattice (static)")
    body += (
        "def Points \"Crystal\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("crystal_fcc.usda", body)


# ---------------------------------------------------------------------------
# 4 – HYDROGEN ORBITALS  (static Points — 4 000 pts)
# ---------------------------------------------------------------------------

def gen_hydrogen_orbitals() -> None:
    """Monte-Carlo sampled H-atom probability densities for n=1,2,3 — static."""
    rng = np.random.default_rng(99)
    a0 = 1.0  # Bohr radius (normalised)
    all_pts = []

    def _sample(r_max: float, psi_sq, n_pts: int) -> np.ndarray:
        """Rejection sample |psi|^2 in a cube."""
        pts = []
        while len(pts) < n_pts:
            x, y, z = rng.uniform(-r_max, r_max, (3, n_pts * 4))
            r = np.sqrt(x**2 + y**2 + z**2) + 1e-12
            theta = np.arccos(z / r)
            p = psi_sq(r / a0, theta)
            p_max = p.max() + 1e-12
            accept = rng.uniform(0, p_max, len(p)) < p
            pts.extend(zip(x[accept], y[accept], z[accept]))
        return np.array(pts[:n_pts], dtype=np.float32)

    # 1s
    all_pts.append(_sample(4, lambda r, _: np.exp(-2 * r), 800))
    # 2pz
    def psi_2pz(r, theta):
        return (r * np.exp(-r / 2) * np.cos(theta)) ** 2
    all_pts.append(_sample(12, psi_2pz, 1000) * np.array([1, 1, 1]))
    # 3d_z2
    def psi_3dz2(r, theta):
        return (r**2 * np.exp(-r / 3) * (3 * np.cos(theta)**2 - 1)) ** 2
    all_pts.append(_sample(18, psi_3dz2, 1200))

    pts = np.vstack(all_pts).astype(np.float32)
    # Scale to a viewable range
    pts /= 4.0
    widths = [0.05] * len(pts)
    body = _header("Procedurally generated by GitHub Copilot — hydrogen atomic orbitals 1s/2pz/3dz2 (static)")
    body += (
        "def Points \"HOrbitals\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("hydrogen_orbitals.usda", body)


# ---------------------------------------------------------------------------
# 5 – ASTEROID BELT  (static Points — 3 500 pts)
# ---------------------------------------------------------------------------

def gen_asteroid_belt() -> None:
    """Procedural asteroid belt ring with Kirkwood gap — static."""
    rng = np.random.default_rng(2025)
    n = 3500
    # Toroidal ring with gap
    r_inner, r_outer = 2.2, 4.0
    pts = []
    while len(pts) < n:
        r = rng.uniform(r_inner, r_outer)
        # Kirkwood gap around 3.28
        if 3.20 < r < 3.35:
            continue
        theta = rng.uniform(0, 2 * math.pi)
        y = rng.normal(0, 0.1 * (r - r_inner))
        pts.append((r * math.cos(theta), y, r * math.sin(theta)))
    pts = np.array(pts, dtype=np.float32)
    # Size diversity
    sizes = rng.exponential(0.05, n).clip(0.02, 0.25).tolist()
    body = _header("Procedurally generated by GitHub Copilot — asteroid belt with Kirkwood gap (static)")
    body += (
        "def Points \"AsteroidBelt\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(sizes)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("asteroid_belt.usda", body)


# ---------------------------------------------------------------------------
# 6 – NEURON NETWORK  (static Points — ~2 500 pts)
# ---------------------------------------------------------------------------

def gen_neuron_network() -> None:
    """Sparse cortical neuron network with soma + dendrite clouds — static."""
    rng = np.random.default_rng(13)
    n_neurons = 60
    soma = rng.uniform(-3, 3, (n_neurons, 3)).astype(np.float32)

    # Dendritic arbour: cluster of pts around each soma
    dendrite_pts = []
    for s in soma:
        n_d = rng.integers(20, 50)
        spread = rng.uniform(0.15, 0.5)
        dendrite_pts.append(s + rng.normal(0, spread, (n_d, 3)).astype(np.float32))

    # Axon terminals (thin line of pts to a random target soma)
    axon_pts = []
    for i in range(n_neurons):
        j = rng.integers(0, n_neurons)
        steps = 12
        for k in range(steps + 1):
            axon_pts.append(soma[i] * (1 - k / steps) + soma[j] * (k / steps))

    dendrites = np.vstack(dendrite_pts).astype(np.float32)
    axons = np.array(axon_pts, dtype=np.float32)
    pts = np.vstack([soma, dendrites, axons])
    widths = ([0.18] * len(soma) + [0.06] * len(dendrites) + [0.04] * len(axons))
    body = _header("Procedurally generated by GitHub Copilot — sparse cortical neuron network (static)")
    body += (
        "def Points \"NeuronNet\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("neuron_network.usda", body)


# ---------------------------------------------------------------------------
# 7 – FRACTAL TREE  (static Points — ~2 000 pts)
# ---------------------------------------------------------------------------

def gen_fractal_tree() -> None:
    """L-system branching tree rendered as point cloud — static."""
    rng = random.Random(314)

    def grow(pos, direction, length, depth, pts_out):
        if depth == 0 or length < 0.01:
            return
        # Deposit points along this branch
        steps = max(3, int(length * 12))
        for k in range(steps + 1):
            t = k / steps
            pts_out.append((
                pos[0] + direction[0] * length * t,
                pos[1] + direction[1] * length * t,
                pos[2] + direction[2] * length * t,
            ))
        end = (
            pos[0] + direction[0] * length,
            pos[1] + direction[1] * length,
            pos[2] + direction[2] * length,
        )
        # Branch into 2-3 children with random deflections
        n_children = 2 if depth > 3 else rng.randint(2, 3)
        for _ in range(n_children):
            ax = rng.gauss(0, 0.6)
            az = rng.gauss(0, 0.6)
            mag = math.sqrt(direction[0]**2 + direction[1]**2 + direction[2]**2)
            nd = (
                direction[0] + ax * mag * 0.4,
                direction[1],
                direction[2] + az * mag * 0.4,
            )
            nl = math.sqrt(nd[0]**2 + nd[1]**2 + nd[2]**2) + 1e-9
            nd = (nd[0] / nl, nd[1] / nl, nd[2] / nl)
            grow(end, nd, length * rng.uniform(0.62, 0.72), depth - 1, pts_out)

    pts_raw: list[tuple] = []
    grow((0, -2.5, 0), (0, 1, 0), 1.4, depth=8, pts_out=pts_raw)
    pts = np.array(pts_raw, dtype=np.float32)
    # Width tapers with height
    y_range = pts[:, 1].max() - pts[:, 1].min() + 1e-6
    widths = (0.14 * (1.0 - (pts[:, 1] - pts[:, 1].min()) / y_range) + 0.03).tolist()
    body = _header("Procedurally generated by GitHub Copilot — L-system branching tree (static)")
    body += (
        "def Points \"FractalTree\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("fractal_tree.usda", body)


# ---------------------------------------------------------------------------
# 8 – LORENZ ATTRACTOR  (static Points — 10 000 pts)
# ---------------------------------------------------------------------------

def gen_lorenz_attractor() -> None:
    """Lorenz strange attractor trajectory — static."""
    sigma, rho, beta = 10.0, 28.0, 8.0 / 3.0
    dt = 0.005
    x, y, z = 1.0, 0.0, 0.0
    n = 10_000
    pts = np.empty((n, 3), dtype=np.float32)
    for i in range(n):
        dx = sigma * (y - x)
        dy = x * (rho - z) - y
        dz = x * y - beta * z
        x += dx * dt; y += dy * dt; z += dz * dt
        pts[i] = (x, y, z)
    # Normalise to roughly [-3, 3]
    pts -= pts.mean(axis=0)
    pts /= pts.std() * 3.0
    widths = [0.03] * n
    body = _header("Procedurally generated by GitHub Copilot — Lorenz strange attractor (static)")
    body += (
        "def Points \"LorenzAttractor\" {\n"
        f"    point3f[] points = {_fpts(pts)}\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        "}\n"
    )
    _write("lorenz_attractor.usda", body)


# ---------------------------------------------------------------------------
# 9 – OCEAN WAVES  (animated Mesh — 21×21 = 441 verts, 48 frames)
# ---------------------------------------------------------------------------

def gen_ocean_waves() -> None:
    """Gerstner wave ocean surface — animated mesh, 48 frames @ 24 fps."""
    N = 21
    n_frames = 48
    # Grid in [-3, 3]
    xs = np.linspace(-3, 3, N, dtype=np.float32)
    zs = np.linspace(-3, 3, N, dtype=np.float32)
    XX, ZZ = np.meshgrid(xs, zs)  # shape (N, N)
    base_x = XX.ravel()
    base_z = ZZ.ravel()
    n_verts = N * N

    # Wave parameters: (amplitude, wavelength, direction_x, direction_z, speed)
    waves = [
        (0.35, 2.0, 1.0, 0.3, 0.9),
        (0.20, 1.2, -0.7, 1.0, 1.3),
        (0.12, 0.7, 0.5, -0.8, 1.8),
        (0.08, 0.45, 0.9, 0.4, 2.4),
    ]

    def gerstner_y(t: float) -> np.ndarray:
        y = np.zeros(n_verts, dtype=np.float32)
        for amp, wl, dx, dz, spd in waves:
            k = 2 * math.pi / wl
            ln = math.sqrt(dx*dx + dz*dz) + 1e-9
            phi = k * (base_x * dx / ln + base_z * dz / ln) - spd * t
            y += amp * np.sin(phi).astype(np.float32)
        return y

    # Build face topology (quads -> 2 triangles each)
    counts, indices = [], []
    for r in range(N - 1):
        for c in range(N - 1):
            a = r * N + c; b = a + 1; d = a + N; e = d + 1
            counts.extend([3, 3])
            indices.extend([a, b, e, a, e, d])

    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        t = fr / 24.0
        y = gerstner_y(t)
        pts = np.column_stack([base_x, y, base_z]).astype(np.float32)
        frames[fr + 1] = pts

    body = _header(
        "Procedurally generated by GitHub Copilot — Gerstner ocean waves (animated)",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Mesh \"OceanSurface\" {\n"
        f"    int[] faceVertexCounts = {_fint(counts)}\n"
        f"    int[] faceVertexIndices = {_fint(indices)}\n"
        "    uniform token subdivisionScheme = \"none\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("ocean_waves.usda", body)


# ---------------------------------------------------------------------------
# 10 – CLOTH DRAPE  (animated Mesh — 20×20 = 400 verts, 40 frames Verlet)
# ---------------------------------------------------------------------------

def gen_cloth_drape() -> None:
    """Verlet cloth simulation — two corners pinned, draped over sphere.

    Animated mesh, 40 frames @ 24 fps.
    """
    N = 20
    n_steps_per_frame = 12
    n_frames = 40
    dt = 0.016

    # Initial flat grid in xz-plane, raised above origin
    xs = np.linspace(-1.5, 1.5, N, dtype=np.float64)
    zs = np.linspace(-1.5, 1.5, N, dtype=np.float64)
    XX, ZZ = np.meshgrid(xs, zs)
    pos = np.column_stack([XX.ravel(), np.full(N * N, 2.0), ZZ.ravel()])
    prev = pos.copy()
    n_v = N * N
    gravity = np.array([0, -9.8, 0], dtype=np.float64)
    sphere_r = 1.0
    sphere_c = np.array([0.0, 0.5, 0.0])

    # Pin top two corners
    pinned = {0, N - 1}

    # Rest-length constraints (structural + shear + bend)
    constraints: list[tuple[int, int, float]] = []
    rest_struct = 3.0 / (N - 1)
    for r in range(N):
        for c in range(N):
            i = r * N + c
            if c < N - 1:
                constraints.append((i, i + 1, rest_struct))
            if r < N - 1:
                constraints.append((i, i + N, rest_struct))
            if r < N - 1 and c < N - 1:
                d = math.sqrt(2) * rest_struct
                constraints.append((i, i + N + 1, d))
                constraints.append((i + 1, i + N, d))

    def step():
        nonlocal pos, prev
        acc = np.tile(gravity, (n_v, 1))
        vel = pos - prev
        prev = pos.copy()
        pos = pos + vel * 0.998 + acc * dt * dt
        # Pinned
        for pi in pinned:
            pos[pi] = prev[pi]
        # Sphere collision
        d = pos - sphere_c
        dist = np.linalg.norm(d, axis=1, keepdims=True)
        too_close = (dist < sphere_r + 0.02).ravel()
        if too_close.any():
            pos[too_close] = sphere_c + d[too_close] / (dist[too_close] + 1e-9) * (sphere_r + 0.02)
        # Floor
        pos[:, 1] = np.maximum(pos[:, 1], -0.05)
        # Constraints (Jacobi relaxation — 8 passes)
        for _ in range(8):
            for i, j, rest in constraints:
                diff = pos[j] - pos[i]
                dist_c = np.linalg.norm(diff) + 1e-9
                correction = diff * 0.5 * (1 - rest / dist_c)
                if i not in pinned:
                    pos[i] += correction
                if j not in pinned:
                    pos[j] -= correction

    # Build face topology
    counts, indices = [], []
    for r in range(N - 1):
        for c in range(N - 1):
            a = r * N + c; b = a + 1; d = a + N; e = d + 1
            counts.extend([3, 3])
            indices.extend([a, b, e, a, e, d])

    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        for _ in range(n_steps_per_frame):
            step()
        frames[fr + 1] = pos.astype(np.float32)

    body = _header(
        "Procedurally generated by GitHub Copilot — Verlet cloth drape over sphere (animated)",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Mesh \"Cloth\" {\n"
        f"    int[] faceVertexCounts = {_fint(counts)}\n"
        f"    int[] faceVertexIndices = {_fint(indices)}\n"
        "    uniform token subdivisionScheme = \"none\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("cloth_drape.usda", body)


# ---------------------------------------------------------------------------
# 11 – FIREWORKS BURST  (animated Points — 500 pts, 60 frames)
# ---------------------------------------------------------------------------

def gen_fireworks() -> None:
    """Multi-burst pyrotechnic particle simulation — animated, 60 frames @ 24 fps."""
    rng = np.random.default_rng(77)
    n_pts = 500
    n_frames = 60
    g = -4.0

    # Each particle: initial position + velocity
    burst_origins = [
        np.array([0.0, 0.0, 0.0]),
        np.array([1.5, 0.5, -0.8]),
        np.array([-1.2, 0.3, 1.0]),
    ]
    pts_per_burst = n_pts // len(burst_origins)
    pos0 = np.empty((n_pts, 3), dtype=np.float32)
    vel  = np.empty((n_pts, 3), dtype=np.float32)
    burst_t = np.zeros(n_pts, dtype=np.float32)

    for b, origin in enumerate(burst_origins):
        sl = slice(b * pts_per_burst, (b + 1) * pts_per_burst)
        phi   = rng.uniform(0, 2 * math.pi, pts_per_burst)
        theta = rng.uniform(0, math.pi,     pts_per_burst)
        spd   = rng.rayleigh(1.8, pts_per_burst)
        vx = spd * np.sin(theta) * np.cos(phi)
        vy = spd * np.sin(theta) * np.sin(phi)
        vz = spd * np.cos(theta)
        pos0[sl] = origin.astype(np.float32)
        vel[sl]  = np.column_stack([vx, vy, vz]).astype(np.float32)
        burst_t[sl] = b * 18  # stagger bursts by 18 frames

    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        t_f = np.maximum(fr - burst_t, 0) / 24.0
        t_f3 = np.column_stack([t_f, t_f, t_f])
        gravity = np.array([0, g, 0], dtype=np.float32)
        pos = pos0 + vel * t_f3 + 0.5 * gravity * t_f3 ** 2
        # Bounce off ground with damping
        below = pos[:, 1] < 0
        pos[below, 1] = -pos[below, 1] * 0.3
        frames[fr + 1] = pos.astype(np.float32)

    widths = [0.06] * n_pts
    body = _header(
        "Procedurally generated by GitHub Copilot — multi-burst fireworks particles (animated)",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Points \"Fireworks\" {\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("fireworks_burst.usda", body)


# ---------------------------------------------------------------------------
# 12 – SOLAR SYSTEM  (animated Points — 11 pts, 120 frames)
# ---------------------------------------------------------------------------

def gen_solar_system() -> None:
    """8 planets + Moon orbiting the Sun — animated, 120 frames @ 24 fps.

    Orbital radii and periods are stylised (not physically accurate) but
    preserve relative ordering and period ratios.
    """
    n_frames = 120
    # (name, orbit_radius, orbital_period_frames, inclination_deg, size)
    bodies = [
        ("Sun",     0.00, 1e9,  0.0, 0.30),
        ("Mercury", 0.55, 12,   7.0, 0.06),
        ("Venus",   0.80, 20,   3.4, 0.10),
        ("Earth",   1.10, 30,   0.0, 0.11),
        ("Moon",    1.26,  4,   5.1, 0.04),
        ("Mars",    1.50, 50,   1.9, 0.07),
        ("Jupiter", 2.30, 120,  1.3, 0.22),
        ("Saturn",  3.10, 240,  2.5, 0.18),
        ("Uranus",  4.00, 480,  0.8, 0.14),
        ("Neptune", 4.80, 800,  1.8, 0.13),
    ]
    n_pts = len(bodies)
    widths = [b[4] for b in bodies]
    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        pts = []
        earth_angle = 0.0
        for name, r, period, inc_deg, _ in bodies:
            inc = math.radians(inc_deg)
            if name == "Moon":
                angle = 2 * math.pi * fr / period
                # Moon orbits Earth
                ex, ez = r * math.cos(earth_angle), r * math.sin(earth_angle)
                pts.append((
                    ex + 0.16 * math.cos(angle),
                    0.16 * math.sin(angle) * math.sin(inc),
                    ez + 0.16 * math.sin(angle),
                ))
            else:
                angle = 2 * math.pi * fr / period
                if name == "Earth":
                    earth_angle = angle
                pts.append((
                    r * math.cos(angle),
                    r * math.sin(angle) * math.sin(inc),
                    r * math.sin(angle),
                ))
        frames[fr + 1] = np.array(pts, dtype=np.float32)

    body = _header(
        "Procedurally generated by GitHub Copilot — solar system orbital animation",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Points \"SolarSystem\" {\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("solar_system.usda", body)


# ---------------------------------------------------------------------------
# 13 – BLACK HOLE ACCRETION DISK  (animated Points — 600 pts, 72 frames)
# ---------------------------------------------------------------------------

def gen_black_hole_disk() -> None:
    """Keplerian accretion disk + polar jets — animated, 72 frames @ 24 fps."""
    rng = np.random.default_rng(666)
    n_disk = 500
    n_jet  = 100
    n_pts  = n_disk + n_jet
    n_frames = 72

    # Initial orbital params for disk particles
    r0    = rng.uniform(0.3, 3.5, n_disk).astype(np.float32)
    theta0 = rng.uniform(0, 2 * math.pi, n_disk).astype(np.float32)
    inc   = rng.normal(0, 0.15, n_disk).astype(np.float32)    # disk tilt
    ecc   = rng.uniform(0.0, 0.25, n_disk).astype(np.float32) # eccentricity

    # Angular velocity ∝ r^(-3/2) (Keplerian)
    omega0 = (r0 ** -1.5).astype(np.float32)

    # Jet particles (static start, animated y)
    jet_r   = rng.uniform(0, 0.15, n_jet).astype(np.float32)
    jet_phi = rng.uniform(0, 2 * math.pi, n_jet).astype(np.float32)
    jet_y0  = rng.uniform(0, 4.0, n_jet).astype(np.float32)   # phase offset
    jet_spd = rng.uniform(0.8, 2.5, n_jet).astype(np.float32)
    jet_sign = rng.choice([-1, 1], n_jet).astype(np.float32)

    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        t = fr / 24.0
        theta = theta0 + omega0 * t
        r_eff = r0 * (1 + ecc * np.cos(theta))
        x = r_eff * np.cos(theta)
        z = r_eff * np.sin(theta)
        y = r_eff * np.sin(inc)
        disk_pts = np.column_stack([x, y, z]).astype(np.float32)

        jet_y = jet_sign * ((jet_y0 + jet_spd * t) % 4.5)
        jet_pts = np.column_stack([
            jet_r * np.cos(jet_phi),
            jet_y,
            jet_r * np.sin(jet_phi),
        ]).astype(np.float32)

        frames[fr + 1] = np.vstack([disk_pts, jet_pts])

    widths = ([0.07] * n_disk + [0.05] * n_jet)
    body = _header(
        "Procedurally generated by GitHub Copilot — Keplerian black-hole accretion disk with polar jets (animated)",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Points \"AccretionDisk\" {\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("black_hole_disk.usda", body)


# ---------------------------------------------------------------------------
# 14 – SMOKE PLUME  (animated Points — 400 pts, 60 frames)
# ---------------------------------------------------------------------------

def gen_smoke_plume() -> None:
    """Rising turbulent smoke plume — animated, 60 frames @ 24 fps."""
    rng = np.random.default_rng(55)
    n_pts = 400
    n_frames = 60
    recycle_height = 6.0

    pos = rng.uniform([-0.3, 0, -0.3], [0.3, 2.0, 0.3], (n_pts, 3)).astype(np.float32)
    age = rng.uniform(0, 1, n_pts).astype(np.float32)  # 0 = fresh, 1 = old

    def perlin_noise_2d(x: np.ndarray, z: np.ndarray, t: float) -> np.ndarray:
        """Very cheap noise: sum of sine waves at different scales."""
        n = (
            np.sin(x * 2.1 + t * 1.3) * np.cos(z * 1.9 + t * 0.9) * 0.6
            + np.sin(x * 5.3 + t * 2.1) * np.cos(z * 4.7 + t * 1.7) * 0.3
            + np.sin(x * 11.0 + t * 3.5) * 0.1
        )
        return n.astype(np.float32)

    frames: dict[int, np.ndarray] = {}
    for fr in range(n_frames):
        t = fr / 24.0
        # Turbulent horizontal drift increases with height
        spread = 0.15 + pos[:, 1] * 0.08
        vel_x = perlin_noise_2d(pos[:, 0], pos[:, 2], t)          * spread
        vel_z = perlin_noise_2d(pos[:, 2], pos[:, 0], t + 77.3)   * spread
        vel_y = 0.08 + pos[:, 1] * 0.005  # rise slightly faster higher up

        pos[:, 0] += vel_x * 0.04
        pos[:, 1] += vel_y
        pos[:, 2] += vel_z * 0.04
        age += 0.016

        # Recycle particles that escape the top
        escaped = pos[:, 1] > recycle_height
        n_esc = escaped.sum()
        if n_esc:
            pos[escaped] = rng.uniform([-0.2, 0.0, -0.2], [0.2, 0.1, 0.2], (n_esc, 3)).astype(np.float32)
            age[escaped] = 0.0

        frames[fr + 1] = pos.astype(np.float32)

    widths = [0.12] * n_pts
    body = _header(
        "Procedurally generated by GitHub Copilot — turbulent smoke plume (animated)",
        start=1, end=n_frames, fps=24,
    )
    body += (
        "def Points \"SmokePlume\" {\n"
        f"    float[] widths = {_ffl(widths)}\n"
        "    uniform token widthsInterpolation = \"vertex\"\n"
        f"    point3f[] points.timeSamples = {_ts(frames)}\n"
        "}\n"
    )
    _write("smoke_plume.usda", body)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

GENERATORS = [
    ("galaxy_spiral",       gen_galaxy_spiral),
    ("dna_double_helix",    gen_dna_double_helix),
    ("crystal_fcc",         gen_crystal_fcc),
    ("hydrogen_orbitals",   gen_hydrogen_orbitals),
    ("asteroid_belt",       gen_asteroid_belt),
    ("neuron_network",      gen_neuron_network),
    ("fractal_tree",        gen_fractal_tree),
    ("lorenz_attractor",    gen_lorenz_attractor),
    ("ocean_waves",         gen_ocean_waves),
    ("cloth_drape",         gen_cloth_drape),
    ("fireworks_burst",     gen_fireworks),
    ("solar_system",        gen_solar_system),
    ("black_hole_disk",     gen_black_hole_disk),
    ("smoke_plume",         gen_smoke_plume),
]

if __name__ == "__main__":
    print(f"Generating {len(GENERATORS)} USD scenes into {SCENES}/\n")
    for label, fn in GENERATORS:
        print(f"  [{label}]")
        fn()
    print(f"\nDone. {len(GENERATORS)} scenes + existing torus_knot_halo = "
          f"{len(GENERATORS) + 1} total.\n")
    print("Generated files are all labelled")
    print('  "Procedurally generated by GitHub Copilot"')
    print("in their USDA doc strings.")
